# Generated by Django 4.2.17 on 2024-12-26 02:51

from django.db import migrations


def seed_data(apps, schema_editor):
    # Get models
    Tag = apps.get_model("contentmanagement", "Tag")
    Question = apps.get_model("contentmanagement", "Question")
    Option = apps.get_model("contentmanagement", "Option")
    Solution = apps.get_model("contentmanagement", "Solution")
    SolutionStep = apps.get_model("contentmanagement", "SolutionStep")
    User = apps.get_model("auth", "User")

    # Seed Tags
    tag1 = Tag.objects.create(name="Math")
    tag2 = Tag.objects.create(name="Physics")
    tag3 = Tag.objects.create(name="Science")

    # Seed User (ensure a user exists for seeding data)
    author = User.objects.first()
    if not author:
        author = User.objects.create_user(username="seed_user", password="password")

    # Seed Questions
    question1 = Question.objects.create(
        author=author,
        text="The function f(d) = -0.05d + 13.2 models the volume of fuel (in gallons) left in a truck's fuel tank after driving d miles. Based on this model, approximately how many gallons of fuel are consumed for every mile driven?",
        image_url="https://cdn.prod.website-files.com/649aa49e57793ed61ecbd3fd/64decb3e914e4dc884ea355f_1__1_.gif",
    )
    question1.tags.add(tag1, tag2)

    question2 = Question.objects.create(
        author=author,
        text="What is the capital of France?",
        image_url="https://cdn.prod.website-files.com/649aa49e57793ed61ecbd3fd/6736aaa87530b8304ae3686b_Illustration-MAPS_8.png",
    )
    question2.tags.add(tag3)

    # Seed Options
    option1_q1 = Option.objects.create(question=question1, text="0.05", is_correct=True)
    option2_q1 = Option.objects.create(question=question1, text="13.2", is_correct=False)
    option3_q1 = Option.objects.create(question=question1, text="21", is_correct=False)
    option4_q1 = Option.objects.create(question=question1, text="264", is_correct=False)

    option1_q2 = Option.objects.create(question=question2, text="London", is_correct=False)
    option2_q2 = Option.objects.create(question=question2, text="Berlin", is_correct=False)
    option3_q2 = Option.objects.create(question=question2, text="Paris", is_correct=True)
    option4_q2 = Option.objects.create(question=question2, text="Madrid", is_correct=False)

    # Seed Solutions
    solution1 = Solution.objects.create(
        question=question1,
        content="<span class='text-primary'>0.05 is correct.</span>  The function given is:\n<b><color=black>f(d) = -0.05d + 13.2</color></b>\n\nHere, the coefficient of d (which is -0.05) represents the change in the volume of fuel for each additional mile driven. \n\nSince it's negative, it indicates that the truck uses 0.05 gallons for each mile.\n",
        image_url="https://cdn.prod.website-files.com/649aa49e57793ed61ecbd3fd/64decb3ec2beb321a8f9ff6c_6.webp",
    )

    solution2 = Solution.objects.create(
        question=question2,
        content="The correct answer is Paris, the capital of France.",
        image_url="https://cdn.prod.website-files.com/649aa49e57793ed61ecbd3fd/6528af9c46a1e17a1d572dc9_G2D.webp",
    )

    # Seed Solution Steps
    SolutionStep.objects.create(
        solution=solution1,
        title="Step Title 1",
        result="Result Title 1",
        image_url="",
    )
    SolutionStep.objects.create(
        solution=solution1,
        title="Step Title 2",
        result="Result Title 2",
        image_url="",
    )
    SolutionStep.objects.create(
        solution=solution2,
        title="Step Title 1",
        result="Result Title 1",
        image_url="",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("contentmanagement", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
