\set DB_NAME `echo "$DB_NAME"`
\set DB_USER `echo "$DB_USER"`
\set DB_PASSWORD `echo "$DB_PASSWORD"`

-- Create user
CREATE USER :DB_USER WITH PASSWORD :'DB_PASSWORD';
CREATE DATABASE :DB_USER;
GRANT ALL PRIVILEGES ON DATABASE :DB_USER TO :DB_USER;
ALTER ROLE :DB_USER CREATEDB;

-- Create Database of user and allow read/write
CREATE DATABASE :DB_NAME WITH OWNER :DB_USER;
GRANT ALL PRIVILEGES ON DATABASE :DB_NAME TO :DB_USER;
ALTER ROLE :DB_USER CREATEDB;
