name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          DJANGO_ENVIRONMENT: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_ENVIRONMENT: test
      DB_NAME: db_test
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432

    steps:
      - name: Checkout project code
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade wheel
          python -m pip install -r requirements/base.txt
          python -m pip install -r requirements/test.txt

      - name: Apply DB migrations
        run: |
          python manage.py migrate
        env:
          DB_HOST: 127.0.0.1  # Use localhost to avoid DNS resolution issues

      - name: Run tests
        run: |
          pytest -v
        env:
          DB_HOST: 127.0.0.1  # Use localhost to avoid DNS resolution issues
